<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="es">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Sistema de Gestión')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
            ->appendName('language', 'es')
            ->appendName('description', 'Sistema de Gestión de Usuarios y CVs')
            ->appendHttpEquiv('Content-Language', 'es')
        ?>

        <!-- Le styles -->
        <?= $this->headLink([
                                'rel' => 'shortcut icon',
                                'type' => 'image/vnd.microsoft.icon',
                                'href' => $this->basePath() . '/img/favicon.ico'
                            ])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->prependStylesheet('https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css')
?>

        <!-- Scripts -->
        <?= $this->headScript() ?>
    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-dark mb-4" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button
                        class="navbar-toggler"
                        type="button"
                        data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent"
                        aria-expanded="false"
                        aria-label="Toggle navigation"
                    >
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        <i class="fas fa-briefcase me-2"></i>Sistema de Gestión
                    </a>
                </div>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a
                                class="nav-link"
                                href="<?= $this->url('home') ?>"
                            >Home
                            </a>
                        </li>
                        <li class="nav-item">
                            <a
                                class="nav-link"
                                href="<?= $this->url('user') ?>"
                            ><i class="fas fa-users"></i> Usuarios
                            </a>
                        </li>
                        <li class="nav-item">
                            <a
                                class="nav-link"
                                href="<?= $this->url('cvs') ?>"
                            ><i class="fas fa-file-text"></i> CVs
                            </a>
                        </li>
                        <li class="nav-item">
                            <a
                                class="nav-link"
                                href="<?= $this->url('skill') ?>"
                            ><i class="fas fa-cogs"></i> Skills
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            <?= $this->content ?>
            <hr>
            <footer>
                <p>
                    &copy; <?= date('Y') ?>
                    <a href="https://getlaminas.org/">Laminas Project</a> a Series of LF Projects, LLC.
                </p>
            </footer>
        </div>
        <?= $this->inlineScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile('https://code.jquery.com/jquery-3.6.0.min.js') ?>
    </body>
</html>
